[supervisord]
nodaemon = true

[program:aim_server]
command = aim server --repo /opt/aim
stdout_events_enabled = true
stderr_events_enabled = true

[program:aim_ui]
# command = aim ui --repo /opt/aim
command = aim up --repo /opt/aim --host 0.0.0.0
stdout_events_enabled = true
stderr_events_enabled = true


[eventlistener:stdout]
command = supervisor_stdout
buffer_size = 100
events = PROCESS_LOG
result_handler = supervisor_stdout:event_handler

