



---

name: aim_test

services:

  aim_server:
    image: aim_server
    build:
      context: ./Docker/server
      args:
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_USER_ID=${DOCKER_USER_ID}
        - DOCKER_USER_GID=${DOCKER_USER_GID}
    expose:
      - 43800 # UI
      - 53800 # API
    ports:
      - "43800:43800"
    volumes:
      - type: bind
        source: /tmp/aim_RR
        target: /opt/aim
        bind:
          create_host_path: false # Do not create host directory (with root) if dir does not exist

    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://127.0.0.1:43800"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  
  aim_worker:
    image: aim_test_worker
    build:
      context: ./Docker/worker
      args:
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_USER_ID=${DOCKER_USER_ID}
        - DOCKER_USER_GID=${DOCKER_USER_GID}
    command: ["bash", "-c", "pytest ~/test_files/test_aim_runs.py && sleep infinity"]
    # Share .aim volume
    # volumes:
    #   - postgres-db-volume:/opt/supervisord
    depends_on:
      aim_server:
        condition: service_healthy


